Update DID Spec links
perma-id/w3id.org pull request #2062
Opened 2021-03-14 17:43 UTC by OR13

- [ ] Update did spec link
- [ ] Add warning about stale context
- [ ] Add redirect test for did web

2021-03-14 19:18 UTC, dgarijo commented
@OR13,
you are trying to edit a w3id which you did not create.
Can @dlongley approve this PR?

2021-03-14 23:03 UTC, OR13 commented
Related option for did web in the future... https://github.com/w3c-ccg/did-method-web/issues/25

2021-03-15 20:50 UTC, davidlehn commented
See also: https://github.com/perma-id/w3id.org/pull/1653.
@msporny Would be nice to get your input on this too.

2021-03-15 21:38 UTC, davidlehn commented
@OR13 I'm unsure about that did:web change.
- It seems like perhaps it should just be it's own top level thing.  I'm guessing the idea was to prefer a path like /did/did:web:xxx vs /did:web/did:web:xxxx?
- What is the long term intent of that endpoint?  If it might end up as a primary resolver endpoint for a popular did method, there are operational considerations.  There haven't been other use cases like that on w3id.org before (IIRC).

2021-03-18 20:28 UTC, OR13 commented
@davidlehn most to tests saving us from needing to call kubernetes to get a redirect.... currently the universal resolver supports redirects, but its very expensive to manage, would be nice for w3id.org to help resolve did from methods that register a resolver.

I could make another top level path for this like `r`... `https://w3id.org/r/did:web.....`

that would not use the did namespace, I just thought I would try to start with the existing namespace.

2021-04-23 18:49 UTC, OR13 commented
@msporny @dlongley since can you please review?

I am happy to take my did resolver namespace idea to a shorter path like `r`.

2021-05-08 16:44 UTC, OR13 commented
ping @msporny @dlongley @dmitrizagidulin

2021-05-10 17:58 UTC, msporny commented on did/.htaccess
> +RewriteRule ^did:web:(.+)$ https://did-web.web.app/api/v1/identifiers/did:web:$1 [R=302,L]
Let's not mix DID Methods w/ the DID namespace on w3id.org -- can we separate this out to something like: `https://w3id.org/didweb/$1` ?

2021-05-10 17:58 UTC, msporny requested changes
LGTM, except for conflation of did:web with DID spec namespace... we shouldn't cross those streams.

2021-05-10 18:02 UTC, msporny commented on did/.htaccess
>  RewriteRule ^v(.+)$ https://w3c-ccg.github.io/did-spec/contexts/did-v$1.jsonld [R=302,L]
I know this isn't in this PR, but it seems wrong, no? We want to point to did-spec-registries now?

2021-05-10 18:56 UTC, OR13 commented
@msporny  @dlongley @dmitrizagidulin 

please review again :)

2021-05-11 13:55 UTC, dmitrizagidulin approved these changes
:+1:

2021-05-13 12:39 UTC, msporny commented on did/.htaccess
>  RewriteRule ^v(.+)$ https://w3c-ccg.github.io/did-spec/contexts/did-v$1.jsonld [R=302,L]
Yes, that's what I meant, thanks.

2021-05-13 12:41 UTC, msporny approved these changes

2021-05-13 12:41 UTC, merged