add toco ontology
perma-id/w3id.org pull request #2414
Opened 2021-11-26 08:24 UTC by QianruZhou333

2021-11-26 13:25 UTC, dgarijo commented
@QianruZhou333,
your readme file does not seem correct. Can you complete it with a brief description and stating the maintainers pls?

2021-11-26 22:51 UTC, davidlehn commented
Looks like the README.md file is a zip archive.  There's a preview jpg in there that looks like what the README.md should contain.  When you update this, please get the old large zip file out of the git history.  (@dgarijo If that doesn't happen, we should squash it away)

2021-11-27 16:56 UTC, TallTed requested changes
Minor grammar and punctuation tweaks

2021-11-27 16:56 UTC, TallTed commented on toco/README.md
> +ToCo is an ontology for hybrid telecommunication networks. An Device-Interface-Link (DIL) ontology design pattern is proposed for the first time to our knowledge.
```suggestion
ToCo is an ontology for hybrid telecommunication networks. A Device-Interface-Link (DIL) ontology design pattern is proposed for the first time to our knowledge. 
```

2021-11-27 16:56 UTC, TallTed commented on toco/README.md
> +Build around the DIL pattern, the ToCo ontology describes the physical infrastructure, quality of channel, services and users in heterogeneous telecommunication networks which span multiple technolog
```suggestion
Built around the DIL pattern, the ToCo ontology describes the physical infrastructure, quality of channel, services, and users in heterogeneous telecommunication networks which span multiple technology domains across the networks. Examples and use cases of ToCo in recent projects are discussed in publications.
```

2021-11-27 16:56 UTC, TallTed commented on toco/README.md
> +####  $ git clone https://github.com/QianruZhou333/toco_ontology.git
```suggestion
####  `$ git init`
####  `$ git clone https://github.com/QianruZhou333/toco_ontology.git`
```

2023-03-14 09:46 UTC, dgarijo commented
Inactive PR. Closing, please reopen if appropriate

2023-03-14 09:46 UTC, closed without merging