Paradise Ontology permanent id request
perma-id/w3id.org pull request #3558
Opened 2023-08-30 18:49 UTC by beyzayaman

Hi! I'd like to get a permanent ID for our ontology which sits at 

http://ontologies.adaptcentre.ie/paradise/index-en.html

Kind Regards,
Beyza.

2023-08-30 19:43 UTC, dgarijo commented on paradise/.htaccess
> +RewriteRule ^$ index-en.html [R=303,L]
Remove the rewrite base (row 14) and replace lines 21, 25 etc with the links instead please.
For example, here replace `index-en.html` with  `http://ontologies.adaptcentre.ie/paradise/index-en.html`

2023-08-30 20:33 UTC, TallTed requested changes
Small changes for clarity

2023-08-30 20:33 UTC, TallTed commented on paradise/readme.md
> +Ontology
```suggestion
### Ontology
```

2023-08-30 20:33 UTC, TallTed commented on paradise/readme.md
> +Beyza Yaman (beyza.yaman@adaptcentre.ie)
```suggestion
### Maintainers

* Beyza Yaman (beyza.yaman@adaptcentre.ie)
```

2023-08-31 07:39 UTC, beyzayaman commented
Thank you for your suggestions and feedback. I pushed the changes again.

2023-08-31 08:50 UTC, merged