stav: Initial commit
perma-id/w3id.org pull request #3596
Opened 2023-09-25 15:06 UTC by bact

I would like to request for a permanent ID "stav" on w3id.org.
Details are below. Thank you.

STAV: System Trustworthiness and Accountability Vocabulary
Accompanied repo at https://github.com/bact/stav

Contact:
Arthit Suriyawongkul
ADAPT Centre, Trinity College Dublin
arthit.suriyawongkul@adaptcentre.ie

2023-09-25 15:26 UTC, TallTed requested changes

2023-09-25 15:26 UTC, TallTed commented on stav/README.md
> +This document along with source and releases will be available at https://github.com/bact/stav/.
```suggestion
* The canonical URL for STAV is https://w3id.org/stav.
* The namespace for STAV terms is https://w3id.org/stav#, the suggested prefix is stav.
* This document along with source and releases will be available at https://github.com/bact/stav/.
```

2023-09-25 21:06 UTC, bact commented
Sorry, I think I should use the "Add suggestion to batch" instead, to make it one single commit.
Anyway, please kindly review. Thank you.

(if a squashed PR is more preferred, I can close this PR and start a new one as well. Thank you)

2023-09-26 02:08 UTC, davidlehn commented
This PR only has a `README.md`.  Did you forget to add a `.htaccess` file to do redirections?

2023-09-26 04:22 UTC, bact commented
> This PR only has a `README.md`. Did you forget to add a `.htaccess` file to do redirections?

Thank you. .htaccess redirection is now tested and added.

2023-09-26 13:57 UTC, merged

2023-09-26 14:45 UTC, bact commented
Thank you. It works now.