New ontology publication - HALO
perma-id/w3id.org pull request #3765
Opened 2023-12-07 01:39 UTC by navapatn

This pull is requested to test the first version of HALO ontology

2023-12-07 16:58 UTC, dgarijo commented
Please add a small description in your readme file including who the maintainer for this w3id will be.

2023-12-31 09:44 UTC, dgarijo commented
Ping @navapatn

2024-01-08 05:02 UTC, navapatn commented
> Ping @navapatn
 
The description and contact information were added to the readme file

2024-01-08 09:37 UTC, dgarijo commented on halo-ontology/.htaccess
> +RewriteRule ^$ https://github.com/navapatn/halo-ontology/blob/main/ontology/index-en.html [R=303,L]
this rewrite rule will serve a page in github. You can serve it with github pages easily, which is the target doc you are aiming for.

2024-01-08 09:37 UTC, dgarijo commented on halo-ontology/.htaccess
> +RewriteRule ^$ https://github.com/navapatn/halo-ontology/blob/main/ontology/ontology.owl [R=303,L]
same issue as above

2024-01-08 09:38 UTC, dgarijo commented on halo-ontology/.htaccess
> +ErrorDocument 406 /halo-ontology/406.html
/halo-ontology/406.html is not a local page. You should redirect to an html document, as you do above

2024-01-08 09:38 UTC, dgarijo commented
@navapatn please have a look at my comments. As it is, I don't think the redirection is working as you intend

2024-01-08 15:33 UTC, TallTed requested changes
Some tweaks for humans...

2024-01-08 15:33 UTC, TallTed commented on halo-ontology/readme.md
> +categories of hallucinations, compared to others?
```suggestion
Questions our ontology can help us answer include: 
* Are LLMs relatively uniform in which prompts they hallucinate on, or are there 
  significant differences between LLMs?
* What kinds of hallucination categories are most common?
* Furthermore, given longitudinal data, can we determine if LLMs are ‘improving’ 
  on some categories of hallucinations, compared to others?
```

2024-01-08 15:33 UTC, TallTed commented on halo-ontology/readme.md
> +**The Metadata module** represents the core concept and properties of the prompts and answers we gathered such as Generative AI models, LLMs, Prompts_id, Answer_id, etc.
```suggestion
**The Metadata module** represents the core concepts and properties of the prompts and answers we gathered such as Generative AI models, LLMs, Prompts_id, Answer_id, etc.
```

2024-01-08 15:33 UTC, TallTed commented on halo-ontology/readme.md
> +We further sub-categorize it into three subtypes: Instruction Inconsistency, Context Inconsistency, and Logical Inconsistency
```suggestion
1. _Factuality Hallucinations_ refers to errors in LLM outputs that misrepresent
real-world facts. These errors manifest in two distinct ways: _Factual
Inconsistency_ and _Factual Fabrication_.
2. _Faithfulness Hallucination_ refers to LLM outputs that fail to align faithfully
with user instructions, when provided with context, including well-known logical
rules based in objective fields like math or physics, for example. We further
sub-categorize it into three subtypes: _Instruction Inconsistency_, _Context
Inconsistency_, and _Logical Inconsistency_.
```

2024-01-08 15:33 UTC, TallTed commented on halo-ontology/readme.md
> +Contact information: Navapat Nananukul (nananuku@isi.edu)
```suggestion
Contact information: Navapat Nananukul (nananuku@isi.edu) [@navapatn](https://github.com/navapatn) 
```

2024-01-16 04:54 UTC, navapatn commented
@TallTed @dgarijo 
Thank you for both of your suggestions. 
I have made all the changes both in .htaccess and readme.md

2024-01-16 09:23 UTC, dgarijo commented on halo-ontology/.htaccess
> +ErrorDocument 406 https://navapatn.github.io/halo-ontology/ontology/406.html
Have you validated this rule? I do not think line 30 is valid. See https://github.com/perma-id/w3id.org/blob/master/example/.htaccess for an example

2024-01-16 09:24 UTC, dgarijo commented
@navapatn 
Please see my comment about line 30 in your htaccess file

2024-01-17 20:40 UTC, navapatn commented
@dgarijo Thank you for the example, and I'm sorry for the confusion. I have adjusted the file based on the example.

2024-01-18 09:58 UTC, merged