Ontology Modules
perma-id/w3id.org pull request #3781
Opened 2023-12-13 08:37 UTC by RichZele

This pull request introduces a set of new folders into the repository, which serve as placeholders for the ontology modules that will be developed and added in the near future. Each folder includes a `.gitkeep` file to allow them to be committed to the repository, as Git does not track empty directories. The addition of these folders is the first step in organizing the upcoming modules. They will be populated with the relevant ontology files as the development progresses.

2023-12-13 21:25 UTC, RichZele commented
Hi Daniel,
Thank you for your message. The modules are already ready. We are waiting
until the paper is published.
I will commit them soon.

Best regards,
Rahel

On Wed, Dec 13, 2023 at 10:34 AM Daniel Garijo ***@***.***>
wrote:

> Please remove the .gitkeep files. We don't do w3id reservation for now.
> When the modules are ready, then commit them with their corresponding
> redirection files and we'll merge
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/3781#issuecomment-1853565376>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVMEGYT2JOLEHA7CQHCQN3YJFZARAVCNFSM6AAAAABASYJGVWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJTGU3DKMZXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-31 09:43 UTC, dgarijo commented
@RichZele any news on the files to be committed?

2024-01-01 07:22 UTC, RichZele commented
Hi Daniel,

I am just waiting for the publication of the paper in which we introduced
the dpp ontology (digital product passport).
The paper is submitted to a Q1 journal in Elsevier and it is currently
under review... For confirmation, I put the link here:
https://track.authorhub.elsevier.com/?uuid=42d8ebb4-fd5c-4ddb-857f-94908a1521b2


I hope this is ok.

Kind regards,
Rahel

On Sun, Dec 31, 2023 at 10:44 AM Daniel Garijo ***@***.***>
wrote:

> @RichZele <https://github.com/RichZele> any news on the files to be
> committed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/3781#issuecomment-1872906336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVMEG22P3IAM7XTDSWX5EDYMEXWFAVCNFSM6AAAAABASYJGVWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZSHEYDMMZTGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-08 11:16 UTC, dgarijo commented
ping @RichZele for updates about this

2024-04-30 16:55 UTC, davidlehn commented
Ping.  Will close this soon if there's no activity.

2024-05-03 09:45 UTC, RichZele commented
Hi, 
I added all the modules to the dpp directory. 
Kindg regards,
Rahel

2024-05-03 13:52 UTC, davidlehn commented
This service does not support hosting files.  Please use redirects to your hosting service.  Also missing maintainer information.  Look at how all the other ids are setup with `.htaccess` and usually a `README.md`.  When fixing this, please remove all the content files from git history.

2024-05-03 20:25 UTC, TallTed requested changes

2024-05-03 20:25 UTC, TallTed commented on dpp/Certification_Module/8_Certification_Module.ttl
> +    rdfs:comment "Indicates if a product complies with applicable building codes and regulations."@en ;
```suggestion
    rdfs:comment "Indicates whether a product complies with applicable building codes and regulations."@en ;
```

2024-06-28 20:17 UTC, davidlehn commented
Closing this.  Feel free to open another PR that follows the policy of only adding redirects to resources on other sites.

2024-06-28 20:17 UTC, closed without merging