Add new repo: ontove ontology
perma-id/w3id.org pull request #4071
Opened 2024-04-22 16:05 UTC by AlessandroBertozzi

2024-04-22 17:32 UTC, TallTed requested changes
Small grammar and punctuation fixes

2024-04-22 17:32 UTC, TallTed commented on ontove/.htaccess
> +# legal science studies in Bologna, the Italian jurist Irnerius - have been possible by the Collegio di Spagna that
```suggestion
# legal science studies in Bologna, the Italian jurist Irnerius - have been made possible by the Collegio di Spagna that 
```

2024-04-22 17:32 UTC, TallTed commented on ontove/README.md
> +The OntoVE project, Ontologies for the valorization of Germanic Cultural Heritage in Veneto within the perspective of the European Open Science Cloud (EOSC), has as its goal the development of  ontol
```suggestion
The OntoVE project, Ontologies for the valorization of Germanic Cultural Heritage in Veneto within the perspective of the European Open Science Cloud (EOSC), has as its goal the development of ontological modules for the description of Germanic Cultural Heritage (CH) items related to the Veneto region and provision of different visualization outputs designed for both academic and a non-academic audiences.
```

2024-04-22 17:32 UTC, TallTed commented on ontove/README.md
> +The OntoVE_WrittenRecords module has as its centre the semantic description of bibliographic items; it reuses LRMoo v 0.9.6 (Bekiari et al. 2023), Bibframe (https://www.loc.gov/bibframe/implementatio
```suggestion
The OntoVE_WrittenRecords module has as its centre the semantic description of bibliographic items; it reuses LRMoo v 0.9.6 (Bekiari et al. 2023), Bibframe (https://www.loc.gov/bibframe/implementation/), and the Bibo (D’Arcus/Giasson 2016, https://www.dublincore.org/specifications/bibo/) ontology. The modules where developed with Protégé Desktop, version 5.5.0 (http://protege.stanford.edu, Musen 2015). 
```

2024-04-22 17:32 UTC, TallTed commented on ontove/README.md
> +Both modules align semantically equivalent classes and assign classes from finer-grained ontologies as subclasses of the more general and abstract classes provided by CIDOC-CRM and its interoperable
```suggestion
Both modules align semantically equivalent classes and assign classes from finer-grained ontologies as subclasses of the more general and abstract classes provided by CIDOC-CRM and its interoperable bibliographic module LRMoo. By semantic alignment operations and the reuse of established ontologies, the project adheres to the FAIR principles (Kush et al. 2020).
```

2024-04-23 11:18 UTC, dgarijo commented
@AlessandroBertozzi please review suggestions and please clarify who the maintainer for this project will be. As stated in the htaccess it is:
```
# Contacts:
# - Monica Palmirani <monica.palmirani@unibo.it>
# - Silvio Peroni <silvio.peroni@unibo.it>
```
Is this correct? Please add yourself as a maintainer in the readme too

2024-04-23 12:09 UTC, AlessandroBertozzi commented
I added the contacts and made the suggested changes to the texts. Sorry about the little mishap on the .htaccess. It was a text left over from an old project. I corrected and aligned it

2024-04-23 12:23 UTC, merged