bmp
perma-id/w3id.org pull request #4214
Opened 2024-06-25 08:30 UTC by JulKaltenegger

This is a new namespace for the Building Material Performance Ontology.

2024-06-25 09:17 UTC, dgarijo commented
There is no redirection. Please add one, we don't do namespace reservation

2024-06-25 15:56 UTC, TallTed requested changes

2024-06-25 15:56 UTC, TallTed commented on bmp/README.md
> +The Building Material Performance ontology classifies construction materials based on categories, types and property groups. Each property group contains multiple material parameters that are based o
```suggestion
The Building Material Performance ontology classifies construction materials based on categories, types, and property groups. Each property group contains multiple material parameters that are based on building physics and thus enable building information models to be enriched with highly aggregated information with respect to material information modelling and material simulation.
```

2024-06-25 15:56 UTC, TallTed commented on bmp/README.md
> +https://julkaltenegger.github.io/bmp/
```suggestion
## Web Documentation

https://julkaltenegger.github.io/bmp/ 

## Maintainer

@julkaltenegger
```

2024-06-26 07:13 UTC, JulKaltenegger commented
Hello there,

I am trying to figure out what to put into the .htaccess file.  I want to
publish the entire documentation of the ontology to a later stage, when
publishing the paper.
Do you have a reference htaccess doc?

Thanks
Julia

Am Di., 25. Juni 2024 um 17:56 Uhr schrieb Ted Thibodeau Jr <
***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In bmp/README.md
> <https://github.com/perma-id/w3id.org/pull/4214#discussion_r1653102439>:
>
> > @@ -0,0 +1,6 @@
> +# BMP_BuildingMaterialPerformance
> +
> +The Building Material Performance ontology classifies construction materials based on categories, types and property groups. Each property group contains multiple material parameters that are based on building physics and thus enable building information models to be enriched with highly aggregated information with respect to material information modelling and material simulation.
>
> ⬇️ Suggested change
>
> -The Building Material Performance ontology classifies construction materials based on categories, types and property groups. Each property group contains multiple material parameters that are based on building physics and thus enable building information models to be enriched with highly aggregated information with respect to material information modelling and material simulation.
> +The Building Material Performance ontology classifies construction materials based on categories, types, and property groups. Each property group contains multiple material parameters that are based on building physics and thus enable building information models to be enriched with highly aggregated information with respect to material information modelling and material simulation.
>
> ------------------------------
>
> In bmp/README.md
> <https://github.com/perma-id/w3id.org/pull/4214#discussion_r1653107669>:
>
> > +Web Documentation
> +https://julkaltenegger.github.io/bmp/
>
> ⬇️ Suggested change
>
> -Web Documentation
> -https://julkaltenegger.github.io/bmp/
> +## Web Documentation
> +
> +https://julkaltenegger.github.io/bmp/
> +
> +## Maintainer
> +
> ***@***.***
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/4214#pullrequestreview-2139124173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGN3ZIGTEUT7NP5PUUYS7WLZJGHMJAVCNFSM6AAAAABJ3KWJ32VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMZZGEZDIMJXGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-26 09:20 UTC, dgarijo commented
Here is an example: https://github.com/perma-id/w3id.org/tree/master/example

2024-08-14 12:24 UTC, JulKaltenegger commented
Hey,

My apologies for the delay..
I try to understand how this works, Even though I see the reference, I dont
understand if I have to make changes inside the .htaccess or do I simply
c/p in my repo?
I send you also a link of my own repo with the bmp ontology
https://github.com/JulKaltenegger/bmp/tree/main
so you can see that i did make this index.html already, is this the same
thing?

Thank you for clarifying.
Best regards
Julia


Am Mi., 26. Juni 2024 um 11:20 Uhr schrieb Daniel Garijo <
***@***.***>:

> Here is an example:
> https://github.com/perma-id/w3id.org/tree/master/example
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/4214#issuecomment-2191222681>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGN3ZICDRHL3LX2R3MQ5V4DZJKBXPAVCNFSM6AAAAABJ3KWJ32VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJRGIZDENRYGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-14 20:44 UTC, davidlehn commented
w3id.org is only a redirection service.  You need a `.htaccess` here to map requests to redirection responses to your site(s).  To get a minimum mapping so that a browser would send links like `https://w3id.org/bmp#Hempcrete` to that anchor on your doc site, use something like this:
```
RewriteEngine on
RewriteRule ^$ https://julkaltenegger.github.io/bmp/ [R=302,L]
```
If you look around at that above example or many of the other directories you can see examples of redirects based on request type and sub-paths and lots of other things.  Your use case determines what you will want to setup.

2024-09-03 13:21 UTC, JulKaltenegger commented
Finally managed to add .htaccess
Can you check please and tell me if it is good?

Thanks
Julia




Am Mi., 14. Aug. 2024 um 22:44 Uhr schrieb David I. Lehn <
***@***.***>:

> w3id.org is only a redirection service. You need a .htaccess here to map
> requests to redirection responses to your site(s). To get a minimum mapping
> so that a browser would send links like https://w3id.org/bmp#Hempcrete to
> that anchor on your doc site, use something like this:
>
> RewriteEngine on
> RewriteRule ^$ https://julkaltenegger.github.io/bmp/ [R=302,L]
>
> If you look around at that above example or many of the other directories
> you can see examples of redirects based on request type and sub-paths and
> lots of other things. Your use case determines what you will want to setup.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/4214#issuecomment-2289844836>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGN3ZIHDCW3ELCQC6SQWNPLZRO6UDAVCNFSM6AAAAABJ3KWJ32VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBZHA2DIOBTGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-03 13:28 UTC, merged

2024-09-03 13:30 UTC, dgarijo commented on bmp/.htaccess
> +RewriteRule ^$ https://julkaltenegger.github.io/bmp/406.xml [R=303,L]
Careful, this does not exist. I think you want to add https://julkaltenegger.github.io/bmp/ontology.xml instead

2024-09-03 13:30 UTC, dgarijo commented on bmp/.htaccess
> +RewriteRule ^$https://julkaltenegger.github.io/bmp/406.html [R=303,L]
This is not the right redirection. You may want to redirect to `https://julkaltenegger.github.io/bmp/ontology.ttl ` instead

2024-09-03 13:31 UTC, dgarijo commented on bmp/.htaccess
> +RewriteRule ^$https://julkaltenegger.github.io/bmp/406.html [R=303,L]
Also leave a space between `^$` and `https`

2024-09-03 13:31 UTC, dgarijo commented
@JulKaltenegger I merged but there are a few typos which I highlighted in my review. Please have a look

2024-09-04 06:12 UTC, JulKaltenegger commented
Hey,

Thanks for the check and response. I updated the file and committed again.
Could you check again if it is good to go?






Am Di., 3. Sept. 2024 um 15:32 Uhr schrieb Daniel Garijo <
***@***.***>:

> @JulKaltenegger <https://github.com/JulKaltenegger> I merged but there
> are a few typos which I highlighted in my review. Please have a look
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/4214#issuecomment-2326538356>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGN3ZIADUAC56GAXUFJZKA3ZUW25ZAVCNFSM6AAAAABJ3KWJ32VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRWGUZTQMZVGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-04 10:28 UTC, dgarijo commented
you need to open a new PR

2024-09-04 12:02 UTC, JulKaltenegger commented
What do you mean by PR?\





Am Mi., 4. Sept. 2024 um 12:29 Uhr schrieb Daniel Garijo <
***@***.***>:

> you need to open a new PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/4214#issuecomment-2328502763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGN3ZIB2X4QPBLHZCAURRMDZU3OG3AVCNFSM6AAAAABJ3KWJ32VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRYGUYDENZWGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-04 12:03 UTC, dgarijo commented
you opened a pull request (PR), and we merged it. Now if you added more changes, you  need to open a new one.