Add identifier dfgfo (WIP)
perma-id/w3id.org pull request #4348
Opened 2024-08-14 06:13 UTC by SArndt-TIB

Hi, this is our first draft for an ontology identifier. It's WIP - we will still update some targets and probably come back for further edits. Thanks for merging and all the best, Susanne

2024-08-14 17:35 UTC, TallTed requested changes

2024-08-14 17:35 UTC, TallTed commented on dfgfo/README.md
> +|<https://w3id.org/dfgfo/2024/<termID>>|text/html|<https://terminology.tib.eu/ts/ontologies/dfgfo2024/terms?iri=https%3A%2F%2Fw3id.org%2Fdfgfo%2F2024%2F<termID>>|Landing page of a specific DFGFO 2024
```suggestion
|<https://w3id.org/dfgfo/2024>|`text/turtle`|<https://raw.githubusercontent.com/tibonto/DFG-Fachsystematik-Ontology/2024-YYYY-MM-DD/dfgfo.ttl>|Turtle file (.ttl) of the entire ontology (2024 version)|
|<https://w3id.org/dfgfo/2024>|`text/html`|<https://terminology.tib.eu/ts/ontologies/dfgfo2024>|Landing page of DFGFO 2024 at the TIB Terminology Service|
|<https://w3id.org/dfgfo/2024/%3CtermID%3E>|`text/html`|<https://terminology.tib.eu/ts/ontologies/dfgfo2024/terms?iri=https%3A%2F%2Fw3id.org%2Fdfgfo%2F2024%2F%3CtermID%3E>|Landing page of a specific DFGFO 2024 term at the TIB Terminology Service; for example, for term `3.16-01 Preparatory and Physical Chemistry of Polymer`, the `termID` would be `3.16-01`|
```

2024-08-14 17:35 UTC, TallTed commented on dfgfo/README.md
> +|<https://w3id.org/dfgfo/2020/<termID>>|text/html|<https://terminology.tib.eu/ts/ontologies/dfgfo/terms?iri=https%3A%2F%2Fgithub.com%2Ftibonto%2Fdfgfo%2F<termID>>|Landing page of a specific DFGFO 202
```suggestion
|<https://w3id.org/dfgfo/2020>|`text/turtle`|<https://raw.githubusercontent.com/tibonto/DFG-Fachsystematik-Ontology/2023-01-17/dfgfo.ttl>|Turtle file (`.ttl`) of the entire ontology (2020 version)|
|<https://w3id.org/dfgfo/2020>|`text/html`|<https://terminology.tib.eu/ts/ontologies/dfgfo>|Landing page of DFGFO 2020 at the TIB Terminology Service|
|<https://w3id.org/dfgfo/2020/%3CtermID%3E>|`text/html`|<https://terminology.tib.eu/ts/ontologies/dfgfo/terms?iri=https%3A%2F%2Fgithub.com%2Ftibonto%2Fdfgfo%2F%3CtermID%3E>|Landing page of a specific DFGFO 2020 term at the TIB Terminology Service; for example, for term `44 Computer Science, Systems and Electrical Engineering`, the `termID` would be `44`|
```

2024-08-16 07:44 UTC, SArndt-TIB commented
@dgarijo I have commited the suggestions. @TallTed Thanks!

2024-08-16 08:45 UTC, merged