Add json-ld context redirect for LDES
perma-id/w3id.org pull request #4600
Opened 2024-12-16 15:15 UTC by brechtvdv

2024-12-16 15:53 UTC, pietercolpaert requested changes
I wouldn’t refer it to the jsdelivr anymore. This was a historic decision as github used to not support .jsonld and .ttl files properly. Can you change it to a subpath of https://semiceu.github.io/LinkedDataEventStreams/ and also change line 9 while on it?

2024-12-18 14:11 UTC, dgarijo commented on ldes/.htaccess
> +RewriteRule ^context(.jsonld)?$ https://semiceu.github.io/LinkedDataEventStreams/context.jsonld [R=303,L]
this link is a 404

2024-12-18 14:12 UTC, dgarijo commented
@pietercolpaert since you did an oiginal review, please re-review the changes. Thanks!

2024-12-18 14:13 UTC, pietercolpaert commented
Changes look good. 404 is accurate: the pull request on the context.jsonld in LDES will be merged later

2024-12-18 14:14 UTC, merged